Sport.create(name: "Tennis", players: 4, country_of_origin: "US")
Sport.create(name: "Football", players: 11, country_of_origin: "Brazil")
Sport.create(name: "Baseball", players: 8, country_of_origin: "France")
Sport.create(name: "Ice Hockey", players: 11, country_of_origin: "uk")
Sport.create(name: "Soccer", players: 20, country_of_origin: "Argentine")
Sport.create(name: "Ping-Pong", players: 4, country_of_origin: "M")
Sport.create(name: "baseball", players: 20, country_of_origin: "A")
Sport.create(name: "cricket", players: 12, country_of_origin: "AB")
Sport.create(name: "American Football", players: 20, country_of_origin: "America")